### ISSUE TITLE
Undefined index slug after module creation

### ISSUE THREAD

**Issue by ChristianGiupponi** [caffeinated/modules#163] opened 2016-03-18 18:10 UTC
I have just installed the package and run:

`php artisan make:module Settings``

At the end of the process if I visit my site I get:

```
ErrorException in Modules.php line 313:
Undefined index: slug
```

I have checked the `storage/app/modules.json` and the `slug` is not set.  
If I add it manually the site works.

**Comment by ChristianGiupponi** [comment] 2016-03-19 07:54
I have noticed that this problem is related to the namespace, if I do not set any namespace but the default one it works.  
If I set a custom namespace it fails

**Comment by kaidesu** [comment] 2016-03-19 19:04
Thanks for the info, I'll take a look into this~

**Comment by Uhelliton** [comment] 2016-08-01 22:32
The error still exists !!!

**Comment by drjonnicholson** [comment] 2016-09-11 13:38
For me (Laravel 5.3 fresh install" this can be reproduced as follows:

Create a new module, and when typing a description try using backspace to delete some text such as to correct a spelling. The description in the ui looks correct, but the description text in the app/Modules/MyModule/module.json file looks something like this:
"what I want to tyoe [D[D[D[D[Dtype"

From this point you will get an error complaining about an undefined index: slug.

The consequence of those characters appearing in the description is that the storage/app/modules.json file is generated incorrectly and contains only 4 (basename, id, enabled, order) out of the expected 8 (basename, name, slug, version, description, id, enabled, order) properties for the module. Since the slug property is missing, it appears a good guess this is the source of the issue.

Workarounds:
A) Delete your module and its entry from storage/app/modules.json file. This works for me as I've got nothing in the modules to worry about yet
B) Edit the storage/app/modues.json file to have logical values for the missing properties. I've not tested this as in my case solution A is easier, but should work in theory.

**Comment by A-Lawrence** [comment] 2016-12-20 01:24
Original issue reported by @ChristianGiupponi is resolved in the latest version(s) - especially since you can't specify the Namespace in the generator.

@drjonnicholson how are you running the command? What environment? What terminal? I think this is more likely a user error than an error with this package.

**Comment by zf329398320** [comment] 2017-01-13 11:22
The error still exists !!! hope to fixed ,help~~~

**Comment by vpakg** [comment] 2017-01-16 15:19
Laravel Version: 5.3.28
caffeinated/modules: 4.1
PHP Version: 7.1
Database Driver & Version: 15.1 Distrib 10.1.20-MariaDB

--------------------------------------------------------
I'm also experiencing the same problem. The workaround described by @drjonnicholson fixed the problem for me.

**Comment by beeInteractive** [comment] 2017-01-30 14:26
I had the same issue, check your file encoding or maybe some accent in the module description. It worked for me to save the file **/app/Modules/your-module/module.json** in UTF-8.

**Comment by oLDu67** [comment] 2017-02-06 15:54
i solved this problem. i added to   `"namespace": "Article",`  part of module in  storage/app/modules.json
For example : 

 ```
 "Article": {
        "basename": "Article",
        "name": "Article",
        "slug": "article",
        "namespace": "Article",
        "version": "1.0",
        "description": "This is the description for the Article module.",
        "id": 37359206,
        "order": 9001,
        "enabled": true
    },
```

**Closed** 2017-05-26 21:21 UTC
Labels: Bug
